vrend: Decrease max shader samplers number.
The commit 328e5f668c2b497225f3b59883fc923be8527272 ("vrend: fix
incorrect limit sent for max samplers") was intended to fix the logic of
sending correctly max sampler to guest side, but on the QTI SA8155p
platform (GL_MAX_TEXTURE_IMAGE_UNITS is 16) it resulted in incorrect
decision by Mesa how many samplers to use.

The following error message can be observed when compiling and linking a
shader w/ 32 samplers:

Error linking program:
Error: Sampler Sampler location or component exceeds max allowed.

The commit talks about on-going work to streamline the semantics of the
caps. Unfortunately, no issue id can be found of this activity. Hence,
for the purpose of fixing the linker error, hardcode platform max
samplers value to 16.

Issue: COQOS-20552
Change-Id: Icc257804a42d1411f61307f1912efaea9f15c28b